### ISSUE TITLE
Cannot connect to broker if the program is on docker container

### ISSUE THREAD

**Issue by alifmufthi91** [lovoo/goka#419]
i am not sure where to start, so i am new to Kafka and Goka, and i was developing program locally while running kafka on docker container it runs fine, but when i moved the program to the docker alongside with the kafka in the docker compose, the program wont connect to the broker.

this is how the compose file looks like
```
version: '3'
services:
  app:
    container_name: app
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    logging:
      options:
        max-size: 50m
    env_file:
      - .env
  kafkazookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: kafkazookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafkabroker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafkabroker
    ports:
      - "9092:9092"
    depends_on:
      - kafkazookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "kafkazookeeper:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafkabroker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
```

and this is how i tried to connect to the broker
```
var (
	Brokers             []string
	TopicDeposit        goka.Stream = "deposits"
	TMC                 *goka.TopicManagerConfig
	BalanceGroup        goka.Group = "balance"
	BalanceTable        goka.Table = goka.GroupTable(BalanceGroup)
	AboveThresholdGroup goka.Group = "aboveThreshold"
	AboveThresholdTable goka.Table = goka.GroupTable(AboveThresholdGroup)
)

func InitGoka() {
	logger.Info("Init Goka configuration")

	Brokers = []string{"kafkabroker:9092", "kafkabroker:29092"}
	logger.Info("brokers : %v", Brokers)

	ctx, cancel := context.WithCancel(context.Background())
	grp, ctx := errgroup.WithContext(ctx)

	defer cancel()

	grp.Go(EnsureStreamExists(string(TopicDeposit), Brokers))
	grp.Go(EnsureStreamExists(string(BalanceTable), Brokers))
	grp.Go(EnsureStreamExists(string(AboveThresholdTable), Brokers))

	if err := grp.Wait(); err != nil {
		panic(err)
	}

}

func createTopicManager(brokers []string) goka.TopicManager {
	TMC = goka.NewTopicManagerConfig()
	TMC.Table.Replication = 1
	TMC.Stream.Replication = 1

	config := goka.DefaultConfig()
	config.Consumer.IsolationLevel = sarama.ReadCommitted
	config.Consumer.Offsets.Initial = sarama.OffsetOldest

	goka.ReplaceGlobalConfig(config)

	tm, err := goka.NewTopicManager(brokers, goka.DefaultConfig(), TMC)
	if err != nil {
		logger.Error("Error creating topic manager: %v", err)
		panic(err)
	}
	return tm
}

func EnsureStreamExists(topic string, brokers []string) func() error {
	return func() error {
		logger.Info("Ensuring topic %s exists", topic)
		tm := createTopicManager(brokers)
		defer tm.Close()
		err := tm.EnsureStreamExists(topic, 8)
		if err != nil {
			logger.Error("Error creating kafka topic %s: %v", topic, err)
		}
		return err
	}
}
```
this is the error i get
`panic: Error creating topic manager: cannot connect to broker localhost:9092: dial tcp 127.0.0.1:9092: connect: connection refused`
